name: GitHub Actions Demo
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: "main"
      - run: "curl https://bfc-test.https12345678.repl.co/test.php?update=true&testall=true&updatebadges=true"